# Generated by Django 5.2.8 on 2026-04-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(blank=True, max_length=200, null=True)),
                ('student_name', models.CharField(max_length=200)),
                ('tutor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('description', models.TextField()),
                ('time', models.CharField(max_length=200)),
                ('status', models.CharField(default='Pending', max_length=10)),
            ],
        ),
    ]
