# Generated by Django 5.2.8 on 2026-04-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutoring_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='decline_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
