# Generated by Django 5.2.8 on 2026-03-25 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='price',
            new_name='price_per_hour',
        ),
    ]
