# Generated by Django 5.2.8 on 2026-04-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_rename_price_tutor_price_per_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='image',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
