# Generated by Django 5.2.8 on 2026-04-05 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_alter_tutor_availability'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='availability_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
